<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE Scheduler [
 <!ELEMENT Scheduler (Courses,Rooms)>
 <!ELEMENT Courses (Course*)>
 <!ELEMENT Rooms (Room*)>
 <!ELEMENT Course (GivenIn*)>
 <!ELEMENT GivenIn (Lecture*)>
 <!ELEMENT Lecture EMPTY>
 <!ELEMENT Room EMPTY>
 <!ATTLIST Course
   code ID #REQUIRED
   name CDATA #REQUIRED >
 <!ATTLIST GivenIn
   period CDATA #REQUIRED
   teacher CDATA #IMPLIED
   nrStudents CDATA "0" >
 <!ATTLIST Lecture
   weekday CDATA #REQUIRED
   hour CDATA #REQUIRED
   room IDREF #IMPLIED >
 <!ATTLIST Room
   name ID #REQUIRED
   nrSeats CDATA #IMPLIED >
]>

<Scheduler>
 <Courses>
  <Course code="TDA357"
     name="Databases">
   <GivenIn period="2"
      teacher="Niklas Broberg"
      nrStudents="138">
    <Lecture weekday="Monday"
       hour="13:15" room="VR" />
    <Lecture weekday="Thursday"
       hour="10:00" room="HB1" />
   </GivenIn>
   <GivenIn period="4"
      teacher="Rogardt Heldal">
   </GivenIn>
  </Course>
 </Courses>
 <Rooms>
  <Room name="VR" nrSeats="216"/>
  <Room name="HB1" nrSeats="184"/>
 </Rooms>
</Scheduler>
